# Generated by Django 6.0.7 on 2026-08-05 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawdownHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawdown', models.DecimalField(decimal_places=4, max_digits=10)),
                ('peak_value', models.DecimalField(decimal_places=10, max_digits=30)),
                ('current_value', models.DecimalField(decimal_places=10, max_digits=30)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawdowns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquityCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_curve', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=10, max_digits=30)),
                ('interval', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.tradingpair')),
            ],
        ),
        migrations.CreateModel(
            name='MarketStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_24h', models.DecimalField(decimal_places=10, max_digits=30)),
                ('high_24h', models.DecimalField(decimal_places=10, max_digits=30)),
                ('low_24h', models.DecimalField(decimal_places=10, max_digits=30)),
                ('change_24h', models.DecimalField(decimal_places=4, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.tradingpair')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharpe_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('sortino_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('max_drawdown', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('volatility', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=100)),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('net_profit', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('win_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('winning_trades', models.PositiveIntegerField(default=0)),
                ('losing_trades', models.PositiveIntegerField(default=0)),
                ('total_profit', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('total_loss', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade_statistics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyPortfolioSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_balance', models.DecimalField(decimal_places=10, max_digits=30)),
                ('total_pnl', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('total_assets', models.PositiveIntegerField(default=0)),
                ('snapshot_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'snapshot_date')},
            },
        ),
    ]
