# Generated by Django 6.0.7 on 2026-08-05 15:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('crypto', 'Crypto'), ('stock', 'Stock'), ('forex', 'Forex'), ('commodity', 'Commodity'), ('index', 'Index')], default='crypto', max_length=20)),
                ('precision', models.PositiveSmallIntegerField(default=8)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('website', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBookSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker_fee', models.DecimalField(decimal_places=5, max_digits=8)),
                ('taker_fee', models.DecimalField(decimal_places=5, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('price', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBookLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=4)),
                ('price', models.DecimalField(decimal_places=10, max_digits=30)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='finance.orderbooksnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_balance', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('total_pnl', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('base_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_pairs', to='finance.asset')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='finance.exchange')),
                ('quote_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_pairs', to='finance.asset')),
            ],
            options={
                'unique_together': {('exchange', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('price', models.DecimalField(decimal_places=10, max_digits=30)),
                ('fee', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='finance.order')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.tradingpair')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('average_price', models.DecimalField(decimal_places=10, max_digits=30)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.tradingpair')),
            ],
        ),
        migrations.AddField(
            model_name='orderbooksnapshot',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderbooks', to='finance.tradingpair'),
        ),
        migrations.AddField(
            model_name='order',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.tradingpair'),
        ),
        migrations.CreateModel(
            name='IndicatorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minute'), ('15m', '15 Minute'), ('1h', '1 Hour'), ('4h', '4 Hour'), ('1d', '1 Day')], max_length=5)),
                ('rsi', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ema_20', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('ema_50', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('macd', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('signal', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.tradingpair')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=10, max_digits=30)),
                ('triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.tradingpair')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('locked', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('buy', 'Buy'), ('sell', 'Sell'), ('fee', 'Fee'), ('transfer', 'Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=30)),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minute'), ('15m', '15 Minute'), ('1h', '1 Hour'), ('4h', '4 Hour'), ('1d', '1 Day')], max_length=5)),
                ('open', models.DecimalField(decimal_places=10, max_digits=30)),
                ('high', models.DecimalField(decimal_places=10, max_digits=30)),
                ('low', models.DecimalField(decimal_places=10, max_digits=30)),
                ('close', models.DecimalField(decimal_places=10, max_digits=30)),
                ('volume', models.DecimalField(decimal_places=10, max_digits=30)),
                ('timestamp', models.DateTimeField()),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='finance.tradingpair')),
            ],
            options={
                'unique_together': {('pair', 'interval', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.tradingpair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pair')},
            },
        ),
    ]
